"""add current_index to quiz_sessions

Revision ID: be881f698201
Revises: 86dc1cd9a84c
Create Date: 2025-07-23 13:35:46.684380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be881f698201'
down_revision: Union[str, Sequence[str], None] = '86dc1cd9a84c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # 1) add it as nullable with a default so it can apply
    op.add_column(
        "quiz_sessions",
        sa.Column("current_index", sa.Integer(), nullable=True, server_default="0"),
    )
    # 2) backfill existing rows (now safe because default '0' is applied)
    op.execute("UPDATE quiz_sessions SET current_index = 0 WHERE current_index IS NULL")
    # 3) change it to NOT NULL and strip the server_default if you want
    op.alter_column(
        "quiz_sessions",
        "current_index",
        nullable=False,
        server_default=None,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_sessions', 'current_index')
    # ### end Alembic commands ###
